# ! 31/05/2025 - Configuración de Railway para usar Docker

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "php -S 0.0.0.0:$PORT -t public/"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[environments.production.deploy]
startCommand = "php -S 0.0.0.0:$PORT -t public/"
