# ! 31/05/2025 - Configuración de Railway para FORZAR Docker

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.production"

[deploy]
startCommand = "php -S 0.0.0.0:$PORT -t public/"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
