lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 7200
    api_token_authenticator:
        enabled: true  # Activar este modo explícitamente para asegurar compatibilidad
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
        cookie:
            enabled: true
            name: jwt_token
    set_cookies:
        jwt_token:
            lifetime: 7200
            samesite: lax
            path: /
            secure: true
            httpOnly: true
