lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: null
    token_ttl: 7200
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
        cookie:
            enabled: true
            name: jwt_token
    set_cookies:
        jwt_token:
            lifetime: 7200
            samesite: lax
            path: /
            secure: true
            httpOnly: true
    remove_token_from_body_when_cookies_used: false
    clock_skew: 10
