monolog:
    channels: ["onboarding"]
    
    handlers:
        # Log general de la aplicación
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        
        # Log específico para onboarding con máximo detalle
        onboarding:
            type: stream
            path: "%kernel.logs_dir%/onboarding.log"
            level: debug
            channels: ["onboarding"]
            
        # Log para errores críticos
        error:
            type: stream
            path: "%kernel.logs_dir%/error.log"
            level: error

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "php://stderr"
                level: debug
            
            onboarding:
                type: stream
                path: "php://stderr"
                level: debug
                channels: ["onboarding"]

when@prod:
    monolog:
        processors:
            - { name: 'monolog.processor.introspection', args: { skipClassesPartials: ['Monolog\\', 'Symfony\\'] }}
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                
            onboarding:
                type: stream
                path: "%kernel.logs_dir%/onboarding.log"
                level: debug
                channels: ["onboarding"]
