monolog:
  channels: ["deprecation", "onboarding"]

  handlers:
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      channels: ["!event"]

    onboarding:
      type: stream
      path: "%kernel.logs_dir%/onboarding.log"
      level: debug
      channels: ["onboarding"]

    error:
      type: stream
      path: "%kernel.logs_dir%/error.log"
      level: error

when@dev:
  monolog:
    handlers:
      main:
        type: stream
        path: "php://stderr"
        level: debug
      onboarding:
        type: stream
        path: "php://stderr"
        level: debug
        channels: ["onboarding"]

when@test:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [404, 405]
        channels: ["!event"]
      nested:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug
      onboarding:
        type: stream
        path: "%kernel.logs_dir%/onboarding.log"
        level: debug
        channels: ["onboarding"]

when@prod:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [404, 405]
        buffer_size: 50
      nested:
        type: stream
        path: "php://stderr"
        level: debug
        formatter: monolog.formatter.json
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine"]
      deprecation:
        type: stream
        channels: [deprecation]
        path: "php://stderr"
        formatter: monolog.formatter.json
