# Cargar primero los controladores personalizados para que tengan precedencia
api_conditions:
    resource: '../../src/Controller/ConditionController.php'
    type: attribute
    prefix: /api

api_platform:
    resource: .
    type: api_platform
    prefix: /api

api_login_check:
    path: /api/login_check
    methods: ['POST']
    defaults:
        _controller: App\Controller\AuthController::login
        _api_resource_class: App\Entity\User
        _api_operation_name: post_login_check
        
api_register:
    path: /api/register
    methods: ['POST']
    defaults:
        _controller: App\Controller\AuthController::register
        _api_resource_class: App\Entity\User
        _api_operation_name: post_register
        _api_respond: true
        
api_logout:
    path: /api/logout
    methods: ['POST']
    defaults:
        _controller: App\Controller\AuthController::logout
        _api_resource_class: App\Entity\User
        _api_operation_name: post_logout
        _api_respond: true

api_insights:
    resource: '../../src/Controller/InsightController.php'
    type: attribute
    prefix: /api

